apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-qis5
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-qis5
    app.kubernetes.io/part-of: quarkus
  name: devfile-sample-code-with-quarkus-qis5
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-qis5
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-qis5
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/e2e-demos-qryd-tenant/quarkus/devfile-sample-code-with-quarkus-qis5@sha256:17c7d81c1451f9f116964354e9ba8700e8964cfbb35bcb9486b8e31dc7dc0160
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
